apiVersion: v1
kind: Secret
metadata:
  name: spicy-secret
type: Opaque
data:
  JWT_SECRET: dGhpc2lzYXNhbXBsZXNlY3JldGtleXdpdGhvdmVyMzJieXRlc2ZvcnNlY3VyaXR5
  SPRING_DATASOURCE_USERNAME: c3BpY3k=
  SPRING_DATASOURCE_PASSWORD: c3BpY3k=
  ADMIN_KEY: dHRlb2tib2traQ==