apiVersion: v1
kind: Secret
metadata:
  name: spicy-secret
type: Opaque
data:
  # 'thisisasamplesecretkeywithover32bytesforsecurity' 문자열을 Base64로 인코딩한 값
  JWT_SECRET: dGhpc2lzYXNhbXBsZXNlY3JldGtleXdpdGhvdmVyMzJieXRlc2ZvcnNlY3VyaXR5
  # spicy -> DB_USERNAME / DB_PASSWORD
  SPRING_DATASOURCE_USERNAME: c3BpY3k=
  SPRING_DATASOURCE_PASSWORD: c3BpY3k=
  # 'tteokbokki' Base64로 인코딩
  ADMIN_KEY: dHRlb2tib2traQ==